# Generated by Django 5.1.1 on 2025-06-17 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lcdtm'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='indicacionesvisitas',
            new_name='ind_fecha_idx',
            old_name='indicacione_fecha_b762b7_idx',
        ),
        migrations.RenameIndex(
            model_name='indicacionesvisitas',
            new_name='ind_historia_idx',
            old_name='indicacione_histori_e75187_idx',
        ),
        migrations.RenameIndex(
            model_name='indicacionesvisitas',
            new_name='ind_his_fecha_idx',
            old_name='indicacione_histori_4b9d3d_idx',
        ),
    ]
