# Generated by Django 5.1.1 on 2025-06-07 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_fix_indices_before_rename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['-fechaAlta']},
        ),
        migrations.RenameIndex(
            model_name='indicacionesvisitas',
            new_name='indicacione_histori_e75187_idx',
            old_name='indicacione_idHisto_248eeb_idx',
        ),
        migrations.RenameIndex(
            model_name='indicacionesvisitas',
            new_name='indicacione_histori_4b9d3d_idx',
            old_name='indicacione_idHisto_0bf324_idx',
        ),
        migrations.AlterField(
            model_name='indicacionesvisitas',
            name='historia_clinica',
            field=models.ForeignKey(db_column='historia_clinica_id', on_delete=django.db.models.deletion.CASCADE, to='main.historiaclinica'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='afiliado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='celular',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='obraSocial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='profesion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
